/*
 * [389] Find the Difference
 *
 * https://leetcode.com/problems/find-the-difference/description/
 *
 * algorithms
 * Easy (51.22%)
 * Total Accepted:    97.6K
 * Total Submissions: 190.6K
 * Testcase Example:  '"abcd"\n"abcde"'
 *
 * 
 * Given two strings s and t which consist of only lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 * 
 * Find the letter that was added in t.
 * 
 * Example:
 * 
 * Input:
 * s = "abcd"
 * t = "abcde"
 * 
 * Output:
 * e
 * 
 * Explanation:
 * 'e' is the letter that was added.
 * 
 */
class Solution {
public:
    char findTheDifference(string s, string t) {
        int i=0;
        int s_count[26],t_count[26];
        while(i<26)
        {
            s_count[i]=0;
            t_count[i]=0;
            i++;
        }
        i=0;
        while(i<s.length())
        {
            s_count[(int)s[i++]-97]++;
        }
        i=0;
        while(i<t.length())
        {
            t_count[(int)t[i++]-97]++;
        }
        i=0;
        while(i<26)
        {
            if(s_count[i]!=t_count[i])
            {
                return (char)(i+97);
            }
            i++;
        }
        return 0;
    }
};
